// <auto-generated />
namespace Batch201910B_10B1_10C.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class MVC1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MVC1));
        
        string IMigrationMetadata.Id
        {
            get { return "202008212033535_MVC1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
